robot_info_transform:
  ros__parameters:

    #mcu通讯串口配置
    serial_baud_rate:   115200        
    uart_port_name:     "/dev/ttyS9"

    #对应的tf名称
    odom_frame_id :     "odom"
    robot_frame_id :    "base_footprint"

    odom_pub_topic :     "/odom/raw"  #odom原始数据话题
    sub_vel_topic :      "cmd_vel"    #接收速度话题